#!/bin/sh
sudo mount -o remount,rw /
sudo echo "Starting setgwmode $1" > /tmp/testlog.txt
sudo echo "Starting setgwmode $1" > /var/testlog.txt
sudo echo "Starting setgwmode $1" > /home/pi-star/testlog.txt


